interface modules {
    readonly "fork.svg": string;
    readonly "like.svg": string;
    readonly "dislike.svg": string;
    readonly "wrench.svg": string;
    readonly "note.svg": string;
    readonly "dmset.svg": string;
    readonly "stethoscope.svg": string;
    readonly "play.svg": string;
    readonly "bioscope.svg": string;
    readonly "palette.svg": string;
    readonly "download.svg": string;
    readonly "warn.svg": string;
    readonly "linechart.svg": string;
    readonly "bell.svg": string;
    readonly "vernier.svg": string;
    readonly "gear.svg": string;
    readonly "migrate.svg": string;
    readonly "blind.svg": string;
}