// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: src/proto/broadcast.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "bilibili.broadcast.v1";

/** 核心包装结构 */
export interface BroadcastFrame {
  /** 请求消息信息 */
  options:
    | FrameOption
    | undefined;
  /** 业务target_path */
  targetPath: string;
  /** 业务pb内容 */
  body: Any | undefined;
}

/** google.protobuf.Any */
export interface Any {
  typeUrl: string;
  value: Uint8Array;
}

/** google.protobuf.Empty */
export interface Empty {
}

/** 请求消息信息 */
export interface FrameOption {
  /**
   * 消息id
   *   - client: 本次连接唯一的消息id，可用于回执
   *   - server: 唯一消息id，可用于上报或者回执
   */
  messageId?:
    | bigint
    | undefined;
  /**
   * frame序号
   *   - client: 客户端应该每次请求时frame seq++，会返回对应的对称req/resp
   *   - server: 服务端下行消息，只会返回默认值：0
   */
  sequence: bigint;
  /**
   * 是否进行消息回执(发出MessageAckReq)
   * downstream 上只有服务端设置为true，客户端响应
   * upstream   上只有客户端设置为true，服务端响应
   * 响应帧禁止设置is_ack，协议上禁止循环
   * 通常只有业务帧才可能设置is_ack, 因为协议栈(例如心跳、鉴权)另有响应约定
   */
  isAck?:
    | boolean
    | undefined;
  /** 业务状态码 */
  status?:
    | Status
    | undefined;
  /** 业务ack来源, 仅downstream时候由服务端填写. */
  ackOrigin?: string | undefined;
}

/** 业务状态码 */
export interface Status {
  /**
   * 业务错误码
   * 当code是[UNKNOWN = 2]时，details为业务详细的错误信息，进行proto any转换成业务码结构体
   */
  code: number;
  /** 对错误码的的解释 */
  message: string;
  /** 是调用方和被调用方约定好的额外的proto结构，包含一些详细的错误处理方案等 */
  details: Any[];
}

/** 鉴权请求，通过authorization验证绑定用户mid */
export interface AuthReq {
  /** 冷启动id，算法uuid，重新起启会变 */
  guid: string;
  /** 连接id，算法uuid，重连会变 */
  connId?:
    | string
    | undefined;
  /** 最后收到的消息id，用于过虑重连后获取未读的消息 */
  lastMsgId?: bigint | undefined;
}

/** 鉴权返回 */
export interface AuthResp {
}

/** 消息回执 */
export interface MessageAckReq {
  /** 消息id */
  ackId: bigint;
  /** ack来源，由业务指定用于埋点跟踪 */
  ackOrigin: string;
  /** 消息对应的target_path，方便业务区分和监控统计 */
  targetPath: string;
}

/**
 * 心跳请求
 * 心跳保活：成功心跳为4分45秒，重试心跳为30s，三次收不到进行重连（不超过5分45）
 */
export interface HeartbeatReq {
}

/** 心跳返回 */
export interface HeartbeatResp {
}

/** 路径订阅请求 */
export interface TargetPath {
  /** 需要订阅的target_paths */
  targetPaths: string[];
}

/** 房间操作请求 */
export interface RoomReq {
  /** {type}://{room_id} 如 video://aid/cid */
  id: string;
  event:
    | { $case: "join"; value: RoomJoinEvent }
    | { $case: "leave"; value: RoomLeaveEvent }
    | { $case: "online"; value: RoomOnlineEvent }
    | { $case: "msg"; value: RoomMessageEvent }
    | undefined;
}

/** 房间操作返回 */
export interface RoomResp {
  /** {type}://{room_id} 如 video://aid/cid */
  id: string;
  event:
    | { $case: "join"; value: RoomJoinEvent }
    | { $case: "leave"; value: RoomLeaveEvent }
    | { $case: "online"; value: RoomOnlineEvent }
    | { $case: "msg"; value: RoomMessageEvent }
    | { $case: "err"; value: RoomErrorEvent }
    | undefined;
}

export interface RoomJoinEvent {
}

export interface RoomLeaveEvent {
}

export interface RoomOnlineEvent {
  online?: number | undefined;
}

export interface RoomMessageEvent {
  targetPath: string;
  body: Any | undefined;
}

export interface RoomErrorEvent {
  status: Status | undefined;
}

function createBaseBroadcastFrame(): BroadcastFrame {
  return { options: undefined, targetPath: "", body: undefined };
}

export const BroadcastFrame: MessageFns<BroadcastFrame> = {
  encode(message: BroadcastFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.options !== undefined) {
      FrameOption.encode(message.options, writer.uint32(10).fork()).join();
    }
    if (message.targetPath !== "") {
      writer.uint32(18).string(message.targetPath);
    }
    if (message.body !== undefined) {
      Any.encode(message.body, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BroadcastFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBroadcastFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.options = FrameOption.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetPath = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.body = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAny(): Any {
  return { typeUrl: "", value: new Uint8Array(0) };
}

export const Any: MessageFns<Any> = {
  encode(message: Any, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.typeUrl !== "") {
      writer.uint32(10).string(message.typeUrl);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Any {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAny();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.typeUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFrameOption(): FrameOption {
  return { sequence: 0n };
}

export const FrameOption: MessageFns<FrameOption> = {
  encode(message: FrameOption, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.messageId !== undefined) {
      if (BigInt.asIntN(64, message.messageId) !== message.messageId) {
        throw new globalThis.Error("value provided for field message.messageId of type int64 too large");
      }
      writer.uint32(8).int64(message.messageId);
    }
    if (message.sequence !== 0n) {
      if (BigInt.asIntN(64, message.sequence) !== message.sequence) {
        throw new globalThis.Error("value provided for field message.sequence of type int64 too large");
      }
      writer.uint32(16).int64(message.sequence);
    }
    if (message.isAck !== undefined) {
      writer.uint32(24).bool(message.isAck);
    }
    if (message.status !== undefined) {
      Status.encode(message.status, writer.uint32(34).fork()).join();
    }
    if (message.ackOrigin !== undefined) {
      writer.uint32(42).string(message.ackOrigin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameOption {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameOption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.messageId = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequence = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isAck = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = Status.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ackOrigin = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseStatus(): Status {
  return { code: 0, message: "", details: [] };
}

export const Status: MessageFns<Status> = {
  encode(message: Status, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    for (const v of message.details) {
      Any.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.details.push(Any.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAuthReq(): AuthReq {
  return { guid: "" };
}

export const AuthReq: MessageFns<AuthReq> = {
  encode(message: AuthReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.guid !== "") {
      writer.uint32(10).string(message.guid);
    }
    if (message.connId !== undefined) {
      writer.uint32(18).string(message.connId);
    }
    if (message.lastMsgId !== undefined) {
      if (BigInt.asIntN(64, message.lastMsgId) !== message.lastMsgId) {
        throw new globalThis.Error("value provided for field message.lastMsgId of type int64 too large");
      }
      writer.uint32(24).int64(message.lastMsgId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.guid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.connId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastMsgId = reader.int64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAuthResp(): AuthResp {
  return {};
}

export const AuthResp: MessageFns<AuthResp> = {
  encode(_: AuthResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMessageAckReq(): MessageAckReq {
  return { ackId: 0n, ackOrigin: "", targetPath: "" };
}

export const MessageAckReq: MessageFns<MessageAckReq> = {
  encode(message: MessageAckReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ackId !== 0n) {
      if (BigInt.asIntN(64, message.ackId) !== message.ackId) {
        throw new globalThis.Error("value provided for field message.ackId of type int64 too large");
      }
      writer.uint32(8).int64(message.ackId);
    }
    if (message.ackOrigin !== "") {
      writer.uint32(18).string(message.ackOrigin);
    }
    if (message.targetPath !== "") {
      writer.uint32(26).string(message.targetPath);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageAckReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageAckReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ackId = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ackOrigin = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetPath = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHeartbeatReq(): HeartbeatReq {
  return {};
}

export const HeartbeatReq: MessageFns<HeartbeatReq> = {
  encode(_: HeartbeatReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHeartbeatResp(): HeartbeatResp {
  return {};
}

export const HeartbeatResp: MessageFns<HeartbeatResp> = {
  encode(_: HeartbeatResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTargetPath(): TargetPath {
  return { targetPaths: [] };
}

export const TargetPath: MessageFns<TargetPath> = {
  encode(message: TargetPath, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.targetPaths) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TargetPath {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTargetPath();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetPaths.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomReq(): RoomReq {
  return { id: "", event: undefined };
}

export const RoomReq: MessageFns<RoomReq> = {
  encode(message: RoomReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    switch (message.event?.$case) {
      case "join":
        RoomJoinEvent.encode(message.event.value, writer.uint32(18).fork()).join();
        break;
      case "leave":
        RoomLeaveEvent.encode(message.event.value, writer.uint32(26).fork()).join();
        break;
      case "online":
        RoomOnlineEvent.encode(message.event.value, writer.uint32(34).fork()).join();
        break;
      case "msg":
        RoomMessageEvent.encode(message.event.value, writer.uint32(42).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.event = { $case: "join", value: RoomJoinEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.event = { $case: "leave", value: RoomLeaveEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.event = { $case: "online", value: RoomOnlineEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.event = { $case: "msg", value: RoomMessageEvent.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomResp(): RoomResp {
  return { id: "", event: undefined };
}

export const RoomResp: MessageFns<RoomResp> = {
  encode(message: RoomResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    switch (message.event?.$case) {
      case "join":
        RoomJoinEvent.encode(message.event.value, writer.uint32(18).fork()).join();
        break;
      case "leave":
        RoomLeaveEvent.encode(message.event.value, writer.uint32(26).fork()).join();
        break;
      case "online":
        RoomOnlineEvent.encode(message.event.value, writer.uint32(34).fork()).join();
        break;
      case "msg":
        RoomMessageEvent.encode(message.event.value, writer.uint32(42).fork()).join();
        break;
      case "err":
        RoomErrorEvent.encode(message.event.value, writer.uint32(50).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.event = { $case: "join", value: RoomJoinEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.event = { $case: "leave", value: RoomLeaveEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.event = { $case: "online", value: RoomOnlineEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.event = { $case: "msg", value: RoomMessageEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.event = { $case: "err", value: RoomErrorEvent.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomJoinEvent(): RoomJoinEvent {
  return {};
}

export const RoomJoinEvent: MessageFns<RoomJoinEvent> = {
  encode(_: RoomJoinEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomJoinEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomJoinEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomLeaveEvent(): RoomLeaveEvent {
  return {};
}

export const RoomLeaveEvent: MessageFns<RoomLeaveEvent> = {
  encode(_: RoomLeaveEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomLeaveEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomLeaveEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomOnlineEvent(): RoomOnlineEvent {
  return {};
}

export const RoomOnlineEvent: MessageFns<RoomOnlineEvent> = {
  encode(message: RoomOnlineEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.online !== undefined) {
      writer.uint32(8).int32(message.online);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomOnlineEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomOnlineEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.online = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomMessageEvent(): RoomMessageEvent {
  return { targetPath: "", body: undefined };
}

export const RoomMessageEvent: MessageFns<RoomMessageEvent> = {
  encode(message: RoomMessageEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetPath !== "") {
      writer.uint32(10).string(message.targetPath);
    }
    if (message.body !== undefined) {
      Any.encode(message.body, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomMessageEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomMessageEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetPath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoomErrorEvent(): RoomErrorEvent {
  return { status: undefined };
}

export const RoomErrorEvent: MessageFns<RoomErrorEvent> = {
  encode(message: RoomErrorEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined) {
      Status.encode(message.status, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomErrorEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomErrorEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = Status.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
