// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: src/proto/DmWebViewReply.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "bilibili.community.service.dm.v1.DmWebViewReply";

export enum PostPanelBizType {
  PostPanelBizTypeNone = 0,
  PostPanelBizTypeEncourage = 1,
  PostPanelBizTypeColorDM = 2,
  PostPanelBizTypeNFTDM = 3,
  PostPanelBizTypeFragClose = 4,
  PostPanelBizTypeRecommend = 5,
  UNRECOGNIZED = -1,
}

export enum RenderType {
  RenderTypeNone = 0,
  RenderTypeSingle = 1,
  RenderTypeRotation = 2,
  UNRECOGNIZED = -1,
}

export enum AvatarType {
  AvatarTypeNone = 0,
  AvatarTypeNFT = 1,
  UNRECOGNIZED = -1,
}

export enum PostStatus {
  PostStatusNormal = 0,
  PostStatusClosed = 1,
  UNRECOGNIZED = -1,
}

export enum CheckboxType {
  CheckboxTypeNone = 0,
  CheckboxTypeEncourage = 1,
  CheckboxTypeColorDM = 2,
  UNRECOGNIZED = -1,
}

export enum ToastFunctionType {
  ToastFunctionTypeNone = 0,
  ToastFunctionTypePostPanel = 1,
  UNRECOGNIZED = -1,
}

export enum ExposureType {
  ExposureTypeNone = 0,
  ExposureTypeDMSend = 1,
  UNRECOGNIZED = -1,
}

export enum BubbleType {
  BubbleTypeNone = 0,
  BubbleTypeClickButton = 1,
  BubbleTypeDmSettingPanel = 2,
  UNRECOGNIZED = -1,
}

export enum DmMaskWallContentType {
  DmMaskWallContentTypeUnknown = 0,
  DmMaskWallContentTypeText = 1,
  DmMaskWallContentTypePic = 2,
  UNRECOGNIZED = -1,
}

export enum DmMaskWallBizType {
  DmMaskWallBizTypeUnknown = 0,
  DmMaskWallBizTypeOGV = 1,
  DmMaskWallBizTypeBizPic = 2,
  DmMaskWallBizTypeMute = 3,
  DmMaskWallBizTypeRecord = 4,
  UNRECOGNIZED = -1,
}

/** 弹幕view返回 */
export interface DmWebViewReply {
  /**
   * 弹幕区是否关闭
   * | 0 | 1 |
   * | :-: | :-: |
   * | 开启 | 关闭 |
   */
  state?: number | undefined;
  text?: string | undefined;
  textSide?:
    | string
    | undefined;
  /** 分段弹幕配置 */
  dmSge:
    | DmSegConfig
    | undefined;
  /** AI云屏蔽弹幕的配置 */
  flag:
    | DanmakuFlagConfig
    | undefined;
  /** 高级弹幕链接地址 （上传到bfs） */
  specialDms: string[];
  /** check box 是否展示 */
  checkBox?:
    | boolean
    | undefined;
  /** 弹幕数 */
  count: bigint;
  /** 指令弹幕 */
  commandDms: CommandDm[];
  /** 用户弹幕配置 */
  playerConfig?:
    | DanmuWebPlayerConfig
    | undefined;
  /** 用户举报弹幕，cid维度屏蔽 */
  reportFilterContent: string[];
  expressions: Expressions[];
  postPanel: PostPanel[];
  activityMeta: string[];
  postPanelV2: PostPanelV2[];
  subViews: DmSubView[];
  qoe?: QoeInfo | undefined;
  maskWalls: DmMaskWall[];
}

/** 分段弹幕配置 */
export interface DmSegConfig {
  pageSize: bigint;
  total: bigint;
}

/** AI云屏蔽弹幕的配置 */
export interface DanmakuFlagConfig {
  /** 云屏蔽等级 */
  recFlag: number;
  /** 云屏蔽文案 */
  recText: string;
  /** 云屏蔽开关 */
  recSwitch: number;
}

/** 指令弹幕 */
export interface CommandDm {
  /** 弹幕id */
  id: bigint;
  /** oid */
  oid: bigint;
  /** mid */
  mid: bigint;
  /** 弹幕指令 */
  command: string;
  /** 弹幕内容 */
  content: string;
  /** 弹幕位置 */
  progress: number;
  /** 创建时间 */
  ctime: string;
  /** 修改时间 */
  mtime: string;
  /** extra */
  extra: string;
  /** id string类型 */
  idstr: string;
}

/**
 * 用户弹幕配置
 *
 * [具体数值意义](https://info.bilibili.co/pages/viewpage.action?pageId=114161867)
 */
export interface DanmuWebPlayerConfig {
  dmSwitch: boolean;
  aiSwitch?: boolean | undefined;
  aiLevel: number;
  blocktop: boolean;
  blockscroll: boolean;
  blockbottom: boolean;
  blockcolor: boolean;
  blockspecial: boolean;
  preventshade?: boolean | undefined;
  dmask?: boolean | undefined;
  opacity: number;
  dmarea?: number | undefined;
  speedplus: number;
  fontsize: number;
  screensync?: boolean | undefined;
  speedsync?: boolean | undefined;
  fontfamily: string;
  bold: boolean;
  fontborder?: number | undefined;
  drawType: string;
}

export interface Expressions {
  data: Expression[];
}

export interface Expression {
  keyword: string[];
  url: string;
  period: Period[];
}

export interface Period {
  start?: bigint | undefined;
  end: bigint;
}

export interface PostPanel {
  start: bigint;
  end: bigint;
  priority: bigint;
  bizId: bigint;
  bizType: PostPanelBizType;
  clickButton: ClickButton | undefined;
  textInput: TextInput | undefined;
  checkBox: CheckBox | undefined;
  toast: Toast | undefined;
}

export interface ClickButton {
  portraitText: string[];
  landscapeText: string[];
  portraitTextFocus: string[];
  landscapeTextFocus: string[];
  renderType: RenderType;
  show: boolean;
  bubble: Bubble | undefined;
}

export interface Bubble {
  text: string;
  url: string;
}

export interface TextInput {
  portraitPlaceholder: string[];
  landscapePlaceholder: string[];
  renderType: RenderType;
  placeholderPost: boolean;
  show: boolean;
  avatar: Avatar[];
  postStatus: PostStatus;
  label: Label | undefined;
}

export interface Avatar {
  id: string;
  url: string;
  avatarType: AvatarType;
}

export interface Label {
  title: string;
  content: string[];
}

export interface CheckBox {
  text: string;
  type: CheckboxType;
  defaultValue: boolean;
  show: boolean;
}

export interface Toast {
  text: string;
  duration: number;
  show: boolean;
  button: Button | undefined;
}

export interface Button {
  text: string;
  action: number;
}

export interface PostPanelV2 {
  start: bigint;
  end: bigint;
  bizType: PostPanelBizType;
  clickButton: ClickButtonV2 | undefined;
  textInput: TextInputV2 | undefined;
  checkBox: CheckBoxV2 | undefined;
  toast: ToastV2 | undefined;
  bubble: BubbleV2 | undefined;
  label: LabelV2 | undefined;
  postStatus: PostStatus;
}

export interface ClickButtonV2 {
  portraitText: string[];
  landscapeText: string[];
  portraitTextFocus: string[];
  landscapeTextFocus: string[];
  renderType: RenderType;
  textInputPost: boolean;
  exposureOnce: boolean;
  exposureType: ExposureType;
}

export interface TextInputV2 {
  portraitPlaceholder: string[];
  landscapePlaceholder: string[];
  renderType: RenderType;
  placeholderPost: boolean;
  textInputLimit: number;
}

export interface CheckBoxV2 {
  text: string;
  type: CheckboxType;
  defaultValue: boolean;
}

export interface ToastV2 {
  text: string;
  duration: number;
  toastButtonV2: ToastButtonV2 | undefined;
}

export interface ToastButtonV2 {
  text: string;
  action: ToastFunctionType;
}

export interface BubbleV2 {
  text: string;
  url: string;
  bubbleType: BubbleType;
  exposureOnce: boolean;
  exposureType: ExposureType;
}

export interface LabelV2 {
  title: string;
  content: string[];
  exposureOnce: boolean;
  exposureType: ExposureType;
}

export interface DmSubView {
  type: number;
  oid: bigint;
  pid: bigint;
  postPanel2: PostPanelV2[];
}

export interface QoeInfo {
  info: string;
}

export interface DmMaskWall {
  start: bigint;
  end: bigint;
  content: string;
  contentType: DmMaskWallContentType;
  bizType: DmMaskWallBizType;
  contents: DmMaskWallContent[];
}

export interface DmMaskWallContent {
  type: DmMaskWallContentType;
  content: string;
}

function createBaseDmWebViewReply(): DmWebViewReply {
  return {
    dmSge: undefined,
    flag: undefined,
    specialDms: [],
    count: 0n,
    commandDms: [],
    reportFilterContent: [],
    expressions: [],
    postPanel: [],
    activityMeta: [],
    postPanelV2: [],
    subViews: [],
    maskWalls: [],
  };
}

export const DmWebViewReply: MessageFns<DmWebViewReply> = {
  encode(message: DmWebViewReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      writer.uint32(8).int32(message.state);
    }
    if (message.text !== undefined) {
      writer.uint32(18).string(message.text);
    }
    if (message.textSide !== undefined) {
      writer.uint32(26).string(message.textSide);
    }
    if (message.dmSge !== undefined) {
      DmSegConfig.encode(message.dmSge, writer.uint32(34).fork()).join();
    }
    if (message.flag !== undefined) {
      DanmakuFlagConfig.encode(message.flag, writer.uint32(42).fork()).join();
    }
    for (const v of message.specialDms) {
      writer.uint32(50).string(v!);
    }
    if (message.checkBox !== undefined) {
      writer.uint32(56).bool(message.checkBox);
    }
    if (message.count !== 0n) {
      if (BigInt.asIntN(64, message.count) !== message.count) {
        throw new globalThis.Error("value provided for field message.count of type int64 too large");
      }
      writer.uint32(64).int64(message.count);
    }
    for (const v of message.commandDms) {
      CommandDm.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.playerConfig !== undefined) {
      DanmuWebPlayerConfig.encode(message.playerConfig, writer.uint32(82).fork()).join();
    }
    for (const v of message.reportFilterContent) {
      writer.uint32(90).string(v!);
    }
    for (const v of message.expressions) {
      Expressions.encode(v!, writer.uint32(98).fork()).join();
    }
    for (const v of message.postPanel) {
      PostPanel.encode(v!, writer.uint32(106).fork()).join();
    }
    for (const v of message.activityMeta) {
      writer.uint32(114).string(v!);
    }
    for (const v of message.postPanelV2) {
      PostPanelV2.encode(v!, writer.uint32(122).fork()).join();
    }
    for (const v of message.subViews) {
      DmSubView.encode(v!, writer.uint32(130).fork()).join();
    }
    if (message.qoe !== undefined) {
      QoeInfo.encode(message.qoe, writer.uint32(138).fork()).join();
    }
    for (const v of message.maskWalls) {
      DmMaskWall.encode(v!, writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DmWebViewReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDmWebViewReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.textSide = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dmSge = DmSegConfig.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.flag = DanmakuFlagConfig.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.specialDms.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.checkBox = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.count = reader.int64() as bigint;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.commandDms.push(CommandDm.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.playerConfig = DanmuWebPlayerConfig.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.reportFilterContent.push(reader.string());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.expressions.push(Expressions.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.postPanel.push(PostPanel.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.activityMeta.push(reader.string());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.postPanelV2.push(PostPanelV2.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.subViews.push(DmSubView.decode(reader, reader.uint32()));
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.qoe = QoeInfo.decode(reader, reader.uint32());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.maskWalls.push(DmMaskWall.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDmSegConfig(): DmSegConfig {
  return { pageSize: 0n, total: 0n };
}

export const DmSegConfig: MessageFns<DmSegConfig> = {
  encode(message: DmSegConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pageSize !== 0n) {
      if (BigInt.asIntN(64, message.pageSize) !== message.pageSize) {
        throw new globalThis.Error("value provided for field message.pageSize of type int64 too large");
      }
      writer.uint32(8).int64(message.pageSize);
    }
    if (message.total !== 0n) {
      if (BigInt.asIntN(64, message.total) !== message.total) {
        throw new globalThis.Error("value provided for field message.total of type int64 too large");
      }
      writer.uint32(16).int64(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DmSegConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDmSegConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDanmakuFlagConfig(): DanmakuFlagConfig {
  return { recFlag: 0, recText: "", recSwitch: 0 };
}

export const DanmakuFlagConfig: MessageFns<DanmakuFlagConfig> = {
  encode(message: DanmakuFlagConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recFlag !== 0) {
      writer.uint32(8).int32(message.recFlag);
    }
    if (message.recText !== "") {
      writer.uint32(18).string(message.recText);
    }
    if (message.recSwitch !== 0) {
      writer.uint32(24).int32(message.recSwitch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DanmakuFlagConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDanmakuFlagConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.recFlag = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.recText = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.recSwitch = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCommandDm(): CommandDm {
  return {
    id: 0n,
    oid: 0n,
    mid: 0n,
    command: "",
    content: "",
    progress: 0,
    ctime: "",
    mtime: "",
    extra: "",
    idstr: "",
  };
}

export const CommandDm: MessageFns<CommandDm> = {
  encode(message: CommandDm, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0n) {
      if (BigInt.asIntN(64, message.id) !== message.id) {
        throw new globalThis.Error("value provided for field message.id of type int64 too large");
      }
      writer.uint32(8).int64(message.id);
    }
    if (message.oid !== 0n) {
      if (BigInt.asIntN(64, message.oid) !== message.oid) {
        throw new globalThis.Error("value provided for field message.oid of type int64 too large");
      }
      writer.uint32(16).int64(message.oid);
    }
    if (message.mid !== 0n) {
      if (BigInt.asIntN(64, message.mid) !== message.mid) {
        throw new globalThis.Error("value provided for field message.mid of type int64 too large");
      }
      writer.uint32(24).int64(message.mid);
    }
    if (message.command !== "") {
      writer.uint32(34).string(message.command);
    }
    if (message.content !== "") {
      writer.uint32(42).string(message.content);
    }
    if (message.progress !== 0) {
      writer.uint32(48).int32(message.progress);
    }
    if (message.ctime !== "") {
      writer.uint32(58).string(message.ctime);
    }
    if (message.mtime !== "") {
      writer.uint32(66).string(message.mtime);
    }
    if (message.extra !== "") {
      writer.uint32(74).string(message.extra);
    }
    if (message.idstr !== "") {
      writer.uint32(82).string(message.idstr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandDm {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommandDm();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.oid = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mid = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.command = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.progress = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ctime = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.mtime = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.extra = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.idstr = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDanmuWebPlayerConfig(): DanmuWebPlayerConfig {
  return {
    dmSwitch: false,
    aiLevel: 0,
    blocktop: false,
    blockscroll: false,
    blockbottom: false,
    blockcolor: false,
    blockspecial: false,
    opacity: 0,
    speedplus: 0,
    fontsize: 0,
    fontfamily: "",
    bold: false,
    drawType: "",
  };
}

export const DanmuWebPlayerConfig: MessageFns<DanmuWebPlayerConfig> = {
  encode(message: DanmuWebPlayerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dmSwitch !== false) {
      writer.uint32(8).bool(message.dmSwitch);
    }
    if (message.aiSwitch !== undefined) {
      writer.uint32(16).bool(message.aiSwitch);
    }
    if (message.aiLevel !== 0) {
      writer.uint32(24).int32(message.aiLevel);
    }
    if (message.blocktop !== false) {
      writer.uint32(32).bool(message.blocktop);
    }
    if (message.blockscroll !== false) {
      writer.uint32(40).bool(message.blockscroll);
    }
    if (message.blockbottom !== false) {
      writer.uint32(48).bool(message.blockbottom);
    }
    if (message.blockcolor !== false) {
      writer.uint32(56).bool(message.blockcolor);
    }
    if (message.blockspecial !== false) {
      writer.uint32(64).bool(message.blockspecial);
    }
    if (message.preventshade !== undefined) {
      writer.uint32(72).bool(message.preventshade);
    }
    if (message.dmask !== undefined) {
      writer.uint32(80).bool(message.dmask);
    }
    if (message.opacity !== 0) {
      writer.uint32(93).float(message.opacity);
    }
    if (message.dmarea !== undefined) {
      writer.uint32(96).int32(message.dmarea);
    }
    if (message.speedplus !== 0) {
      writer.uint32(109).float(message.speedplus);
    }
    if (message.fontsize !== 0) {
      writer.uint32(117).float(message.fontsize);
    }
    if (message.screensync !== undefined) {
      writer.uint32(120).bool(message.screensync);
    }
    if (message.speedsync !== undefined) {
      writer.uint32(128).bool(message.speedsync);
    }
    if (message.fontfamily !== "") {
      writer.uint32(138).string(message.fontfamily);
    }
    if (message.bold !== false) {
      writer.uint32(144).bool(message.bold);
    }
    if (message.fontborder !== undefined) {
      writer.uint32(152).int32(message.fontborder);
    }
    if (message.drawType !== "") {
      writer.uint32(162).string(message.drawType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DanmuWebPlayerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDanmuWebPlayerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dmSwitch = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.aiSwitch = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.aiLevel = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.blocktop = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.blockscroll = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.blockbottom = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.blockcolor = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.blockspecial = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.preventshade = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.dmask = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.opacity = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.dmarea = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.speedplus = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 117) {
            break;
          }

          message.fontsize = reader.float();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.screensync = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.speedsync = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.fontfamily = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.bold = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.fontborder = reader.int32();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.drawType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseExpressions(): Expressions {
  return { data: [] };
}

export const Expressions: MessageFns<Expressions> = {
  encode(message: Expressions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.data) {
      Expression.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Expressions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExpressions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data.push(Expression.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseExpression(): Expression {
  return { keyword: [], url: "", period: [] };
}

export const Expression: MessageFns<Expression> = {
  encode(message: Expression, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.keyword) {
      writer.uint32(10).string(v!);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    for (const v of message.period) {
      Period.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Expression {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExpression();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyword.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.period.push(Period.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePeriod(): Period {
  return { end: 0n };
}

export const Period: MessageFns<Period> = {
  encode(message: Period, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== undefined) {
      if (BigInt.asIntN(64, message.start) !== message.start) {
        throw new globalThis.Error("value provided for field message.start of type int64 too large");
      }
      writer.uint32(8).int64(message.start);
    }
    if (message.end !== 0n) {
      if (BigInt.asIntN(64, message.end) !== message.end) {
        throw new globalThis.Error("value provided for field message.end of type int64 too large");
      }
      writer.uint32(16).int64(message.end);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Period {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.start = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.end = reader.int64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePostPanel(): PostPanel {
  return {
    start: 0n,
    end: 0n,
    priority: 0n,
    bizId: 0n,
    bizType: 0,
    clickButton: undefined,
    textInput: undefined,
    checkBox: undefined,
    toast: undefined,
  };
}

export const PostPanel: MessageFns<PostPanel> = {
  encode(message: PostPanel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== 0n) {
      if (BigInt.asIntN(64, message.start) !== message.start) {
        throw new globalThis.Error("value provided for field message.start of type int64 too large");
      }
      writer.uint32(8).int64(message.start);
    }
    if (message.end !== 0n) {
      if (BigInt.asIntN(64, message.end) !== message.end) {
        throw new globalThis.Error("value provided for field message.end of type int64 too large");
      }
      writer.uint32(16).int64(message.end);
    }
    if (message.priority !== 0n) {
      if (BigInt.asIntN(64, message.priority) !== message.priority) {
        throw new globalThis.Error("value provided for field message.priority of type int64 too large");
      }
      writer.uint32(24).int64(message.priority);
    }
    if (message.bizId !== 0n) {
      if (BigInt.asIntN(64, message.bizId) !== message.bizId) {
        throw new globalThis.Error("value provided for field message.bizId of type int64 too large");
      }
      writer.uint32(32).int64(message.bizId);
    }
    if (message.bizType !== 0) {
      writer.uint32(40).int32(message.bizType);
    }
    if (message.clickButton !== undefined) {
      ClickButton.encode(message.clickButton, writer.uint32(50).fork()).join();
    }
    if (message.textInput !== undefined) {
      TextInput.encode(message.textInput, writer.uint32(58).fork()).join();
    }
    if (message.checkBox !== undefined) {
      CheckBox.encode(message.checkBox, writer.uint32(66).fork()).join();
    }
    if (message.toast !== undefined) {
      Toast.encode(message.toast, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PostPanel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePostPanel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.start = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.end = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priority = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bizId = reader.int64() as bigint;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.bizType = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clickButton = ClickButton.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.textInput = TextInput.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.checkBox = CheckBox.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.toast = Toast.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClickButton(): ClickButton {
  return {
    portraitText: [],
    landscapeText: [],
    portraitTextFocus: [],
    landscapeTextFocus: [],
    renderType: 0,
    show: false,
    bubble: undefined,
  };
}

export const ClickButton: MessageFns<ClickButton> = {
  encode(message: ClickButton, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.portraitText) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.landscapeText) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.portraitTextFocus) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.landscapeTextFocus) {
      writer.uint32(34).string(v!);
    }
    if (message.renderType !== 0) {
      writer.uint32(40).int32(message.renderType);
    }
    if (message.show !== false) {
      writer.uint32(48).bool(message.show);
    }
    if (message.bubble !== undefined) {
      Bubble.encode(message.bubble, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClickButton {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClickButton();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portraitText.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.landscapeText.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portraitTextFocus.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.landscapeTextFocus.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.renderType = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.show = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.bubble = Bubble.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseBubble(): Bubble {
  return { text: "", url: "" };
}

export const Bubble: MessageFns<Bubble> = {
  encode(message: Bubble, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Bubble {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBubble();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTextInput(): TextInput {
  return {
    portraitPlaceholder: [],
    landscapePlaceholder: [],
    renderType: 0,
    placeholderPost: false,
    show: false,
    avatar: [],
    postStatus: 0,
    label: undefined,
  };
}

export const TextInput: MessageFns<TextInput> = {
  encode(message: TextInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.portraitPlaceholder) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.landscapePlaceholder) {
      writer.uint32(18).string(v!);
    }
    if (message.renderType !== 0) {
      writer.uint32(24).int32(message.renderType);
    }
    if (message.placeholderPost !== false) {
      writer.uint32(32).bool(message.placeholderPost);
    }
    if (message.show !== false) {
      writer.uint32(40).bool(message.show);
    }
    for (const v of message.avatar) {
      Avatar.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.postStatus !== 0) {
      writer.uint32(56).int32(message.postStatus);
    }
    if (message.label !== undefined) {
      Label.encode(message.label, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portraitPlaceholder.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.landscapePlaceholder.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.renderType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.placeholderPost = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.show = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.avatar.push(Avatar.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.postStatus = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.label = Label.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAvatar(): Avatar {
  return { id: "", url: "", avatarType: 0 };
}

export const Avatar: MessageFns<Avatar> = {
  encode(message: Avatar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.avatarType !== 0) {
      writer.uint32(24).int32(message.avatarType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Avatar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAvatar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.avatarType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLabel(): Label {
  return { title: "", content: [] };
}

export const Label: MessageFns<Label> = {
  encode(message: Label, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    for (const v of message.content) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Label {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLabel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckBox(): CheckBox {
  return { text: "", type: 0, defaultValue: false, show: false };
}

export const CheckBox: MessageFns<CheckBox> = {
  encode(message: CheckBox, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.defaultValue !== false) {
      writer.uint32(24).bool(message.defaultValue);
    }
    if (message.show !== false) {
      writer.uint32(32).bool(message.show);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckBox {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBox();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultValue = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.show = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseToast(): Toast {
  return { text: "", duration: 0, show: false, button: undefined };
}

export const Toast: MessageFns<Toast> = {
  encode(message: Toast, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.duration !== 0) {
      writer.uint32(16).int32(message.duration);
    }
    if (message.show !== false) {
      writer.uint32(24).bool(message.show);
    }
    if (message.button !== undefined) {
      Button.encode(message.button, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Toast {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToast();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.show = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.button = Button.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseButton(): Button {
  return { text: "", action: 0 };
}

export const Button: MessageFns<Button> = {
  encode(message: Button, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.action !== 0) {
      writer.uint32(16).int32(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Button {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseButton();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.action = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePostPanelV2(): PostPanelV2 {
  return {
    start: 0n,
    end: 0n,
    bizType: 0,
    clickButton: undefined,
    textInput: undefined,
    checkBox: undefined,
    toast: undefined,
    bubble: undefined,
    label: undefined,
    postStatus: 0,
  };
}

export const PostPanelV2: MessageFns<PostPanelV2> = {
  encode(message: PostPanelV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== 0n) {
      if (BigInt.asIntN(64, message.start) !== message.start) {
        throw new globalThis.Error("value provided for field message.start of type int64 too large");
      }
      writer.uint32(8).int64(message.start);
    }
    if (message.end !== 0n) {
      if (BigInt.asIntN(64, message.end) !== message.end) {
        throw new globalThis.Error("value provided for field message.end of type int64 too large");
      }
      writer.uint32(16).int64(message.end);
    }
    if (message.bizType !== 0) {
      writer.uint32(24).int32(message.bizType);
    }
    if (message.clickButton !== undefined) {
      ClickButtonV2.encode(message.clickButton, writer.uint32(34).fork()).join();
    }
    if (message.textInput !== undefined) {
      TextInputV2.encode(message.textInput, writer.uint32(42).fork()).join();
    }
    if (message.checkBox !== undefined) {
      CheckBoxV2.encode(message.checkBox, writer.uint32(50).fork()).join();
    }
    if (message.toast !== undefined) {
      ToastV2.encode(message.toast, writer.uint32(58).fork()).join();
    }
    if (message.bubble !== undefined) {
      BubbleV2.encode(message.bubble, writer.uint32(66).fork()).join();
    }
    if (message.label !== undefined) {
      LabelV2.encode(message.label, writer.uint32(74).fork()).join();
    }
    if (message.postStatus !== 0) {
      writer.uint32(80).int32(message.postStatus);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PostPanelV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePostPanelV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.start = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.end = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bizType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.clickButton = ClickButtonV2.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.textInput = TextInputV2.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.checkBox = CheckBoxV2.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.toast = ToastV2.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bubble = BubbleV2.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.label = LabelV2.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.postStatus = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClickButtonV2(): ClickButtonV2 {
  return {
    portraitText: [],
    landscapeText: [],
    portraitTextFocus: [],
    landscapeTextFocus: [],
    renderType: 0,
    textInputPost: false,
    exposureOnce: false,
    exposureType: 0,
  };
}

export const ClickButtonV2: MessageFns<ClickButtonV2> = {
  encode(message: ClickButtonV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.portraitText) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.landscapeText) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.portraitTextFocus) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.landscapeTextFocus) {
      writer.uint32(34).string(v!);
    }
    if (message.renderType !== 0) {
      writer.uint32(40).int32(message.renderType);
    }
    if (message.textInputPost !== false) {
      writer.uint32(48).bool(message.textInputPost);
    }
    if (message.exposureOnce !== false) {
      writer.uint32(56).bool(message.exposureOnce);
    }
    if (message.exposureType !== 0) {
      writer.uint32(64).int32(message.exposureType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClickButtonV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClickButtonV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portraitText.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.landscapeText.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portraitTextFocus.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.landscapeTextFocus.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.renderType = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.textInputPost = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.exposureOnce = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.exposureType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTextInputV2(): TextInputV2 {
  return {
    portraitPlaceholder: [],
    landscapePlaceholder: [],
    renderType: 0,
    placeholderPost: false,
    textInputLimit: 0,
  };
}

export const TextInputV2: MessageFns<TextInputV2> = {
  encode(message: TextInputV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.portraitPlaceholder) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.landscapePlaceholder) {
      writer.uint32(18).string(v!);
    }
    if (message.renderType !== 0) {
      writer.uint32(24).int32(message.renderType);
    }
    if (message.placeholderPost !== false) {
      writer.uint32(32).bool(message.placeholderPost);
    }
    if (message.textInputLimit !== 0) {
      writer.uint32(48).int32(message.textInputLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextInputV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextInputV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portraitPlaceholder.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.landscapePlaceholder.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.renderType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.placeholderPost = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.textInputLimit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckBoxV2(): CheckBoxV2 {
  return { text: "", type: 0, defaultValue: false };
}

export const CheckBoxV2: MessageFns<CheckBoxV2> = {
  encode(message: CheckBoxV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.defaultValue !== false) {
      writer.uint32(24).bool(message.defaultValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckBoxV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBoxV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultValue = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseToastV2(): ToastV2 {
  return { text: "", duration: 0, toastButtonV2: undefined };
}

export const ToastV2: MessageFns<ToastV2> = {
  encode(message: ToastV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.duration !== 0) {
      writer.uint32(16).int32(message.duration);
    }
    if (message.toastButtonV2 !== undefined) {
      ToastButtonV2.encode(message.toastButtonV2, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToastV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToastV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toastButtonV2 = ToastButtonV2.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseToastButtonV2(): ToastButtonV2 {
  return { text: "", action: 0 };
}

export const ToastButtonV2: MessageFns<ToastButtonV2> = {
  encode(message: ToastButtonV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.action !== 0) {
      writer.uint32(16).int32(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToastButtonV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToastButtonV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.action = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseBubbleV2(): BubbleV2 {
  return { text: "", url: "", bubbleType: 0, exposureOnce: false, exposureType: 0 };
}

export const BubbleV2: MessageFns<BubbleV2> = {
  encode(message: BubbleV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.bubbleType !== 0) {
      writer.uint32(24).int32(message.bubbleType);
    }
    if (message.exposureOnce !== false) {
      writer.uint32(32).bool(message.exposureOnce);
    }
    if (message.exposureType !== 0) {
      writer.uint32(40).int32(message.exposureType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BubbleV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBubbleV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bubbleType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.exposureOnce = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.exposureType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLabelV2(): LabelV2 {
  return { title: "", content: [], exposureOnce: false, exposureType: 0 };
}

export const LabelV2: MessageFns<LabelV2> = {
  encode(message: LabelV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    for (const v of message.content) {
      writer.uint32(18).string(v!);
    }
    if (message.exposureOnce !== false) {
      writer.uint32(24).bool(message.exposureOnce);
    }
    if (message.exposureType !== 0) {
      writer.uint32(32).int32(message.exposureType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LabelV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLabelV2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.exposureOnce = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.exposureType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDmSubView(): DmSubView {
  return { type: 0, oid: 0n, pid: 0n, postPanel2: [] };
}

export const DmSubView: MessageFns<DmSubView> = {
  encode(message: DmSubView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.oid !== 0n) {
      if (BigInt.asIntN(64, message.oid) !== message.oid) {
        throw new globalThis.Error("value provided for field message.oid of type int64 too large");
      }
      writer.uint32(16).int64(message.oid);
    }
    if (message.pid !== 0n) {
      if (BigInt.asIntN(64, message.pid) !== message.pid) {
        throw new globalThis.Error("value provided for field message.pid of type int64 too large");
      }
      writer.uint32(24).int64(message.pid);
    }
    for (const v of message.postPanel2) {
      PostPanelV2.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DmSubView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDmSubView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.oid = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pid = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.postPanel2.push(PostPanelV2.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseQoeInfo(): QoeInfo {
  return { info: "" };
}

export const QoeInfo: MessageFns<QoeInfo> = {
  encode(message: QoeInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== "") {
      writer.uint32(10).string(message.info);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QoeInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQoeInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDmMaskWall(): DmMaskWall {
  return { start: 0n, end: 0n, content: "", contentType: 0, bizType: 0, contents: [] };
}

export const DmMaskWall: MessageFns<DmMaskWall> = {
  encode(message: DmMaskWall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== 0n) {
      if (BigInt.asIntN(64, message.start) !== message.start) {
        throw new globalThis.Error("value provided for field message.start of type int64 too large");
      }
      writer.uint32(8).int64(message.start);
    }
    if (message.end !== 0n) {
      if (BigInt.asIntN(64, message.end) !== message.end) {
        throw new globalThis.Error("value provided for field message.end of type int64 too large");
      }
      writer.uint32(16).int64(message.end);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    if (message.contentType !== 0) {
      writer.uint32(32).int32(message.contentType);
    }
    if (message.bizType !== 0) {
      writer.uint32(40).int32(message.bizType);
    }
    for (const v of message.contents) {
      DmMaskWallContent.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DmMaskWall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDmMaskWall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.start = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.end = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.contentType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.bizType = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contents.push(DmMaskWallContent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDmMaskWallContent(): DmMaskWallContent {
  return { type: 0, content: "" };
}

export const DmMaskWallContent: MessageFns<DmMaskWallContent> = {
  encode(message: DmMaskWallContent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DmMaskWallContent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDmMaskWallContent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
